server:
  port: 8080

naver-api:
  url: https://openapi.naver.com/v1/
  id: wimMMqND6IS9z3VIzppq
  key: l7B0yLlyEy


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        requestVolumeThreshold: 5
        errorThresholdPercentage: 50

feign:
  hystrix:
    enabled: true

logging:
  level:
    com:
      mybloglab:
        blog:
          NaverFeignClients: DEBUG