server:
  port: 8080

spring:
  application:
    name: mybloglab

naver:
  common.url: https://openapi.naver.com/v1/
  ads.url: https://api.naver.com/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        requestVolumeThreshold: 5
        errorThresholdPercentage: 50

feign:
  hystrix:
    enabled: true

logging:
  level:
    root: WARN